---
title: "CORE_EDM_ts_annual_spp_dam"
author: "Kurt Ingeman"
date: "2/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())

library(tidyverse)
library(lubridate)
library(gridExtra)
library(dygraphs)
library(xts)

```

## Data downloaded from Fish Passage Center (FPC) at http://www.fpc.org/fpc_homepage.php

Data are annual counts of all salmon spp at Bonneville (incldes all runs except lower Columbia tribs), Ice Harbor (Snake), and Priest Rapids (upper Columbia).

```{r}
# call in data
bon <- read.csv("data/BON_annual_count.csv")
ihr <- read.csv("data/IHR_annual_count.csv")
prd <- read.csv("data/PRD_annual_count.csv")
```

## Combine and tidy data sets

```{r}
bon$dam <- "bon"
ihr$dam <- "ihr"
prd$dam <- "prd"

td <- bind_rows(bon, ihr, prd) %>% 
  select(-lamprey, -shad, -chum, -pink) %>% 
  gather(key = species, value = counts, -year, -dam)

```

## Plot time series

```{r}

p <- ggplot(td) +
  geom_line(aes(x=year, y=counts, color = species)) +
  theme_classic()

p + facet_grid(species ~ dam)

```


```{r}
# just Bonneville Chinook data
bon.chi <- td %>% 
  filter(species == "chinook_SS" & dam == "bon")

bon.chi$year <- as.numeric(bon.chi$year)

dygraph(bon.chi) %>%
  dyOptions(labelsUTC = TRUE, fillGraph=TRUE, fillAlpha=0.1, drawGrid = FALSE, colors="#D8AE5A") %>%
  dyRangeSelector() %>%
  dyCrosshair(direction = "vertical") %>%
  dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
  dyRoller(rollPeriod = 1)
```

